apiVersion: v1
kind: Secret
metadata:
    name: app-secret
    namespace: default
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:QZE5+xoR90eSR2LQ330=,iv:1/9q22m/xmNVgud5iJEzAxA692T1xathEsZL7FBZXsA=,tag:ZAbD6cxyWNZwD00yynf9kA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zsfflh38n5dk622l6xrgr7r4f97sjggy28jawsav5nvytx5cmf6qxf50de
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnNm9ERkVZcHNOSyt5dUxH
            N3NScDliTzQ1SWR5Q1R6K09QVmw2dHFac2gwClBHVllEMlQ4VXZJdi9HcExVK3FI
            RDFKMThEYWtXTXg3YkRFWFpqV1lFQ2cKLS0tIGFmVENjVCtVeTN1L3BQM2tsVk5z
            WnhRNkhiMW5KY2dSZHY0TWVQY3lDODgKZETMWIwkrBzS832R4KIWzmuM3MQKE+36
            nmRy1gMk2+Dlg1Z94H/o7MoIpLDFk5Ic0Ibj44ja46h109pxfyShIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-12T11:57:56Z"
    mac: ENC[AES256_GCM,data:4qltVCenRIzG64GLo+CFT+ZZ34qJZnMbmbqZN87onLotqRo9it6o2EeV80/x/TCAD032gsacutrGi6CYr1+XrLyqr1FHz4jaY6BaBn1My6FYoUfWWpEeoswe9IhQQsKFASLJ7JZ5CvEiZ+fnv5rFfqCQLlPwkOpCjAsozQcjG5o=,iv:DcoSdGSjZk/vwG3+ZKObWokJABqjx/P+gksyYyFrQBE=,tag:LaJw3cGsDDfhxqVKplt/dQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
